import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

// ─────────────────────────────────────────────────────────────────────────────
// All text uses ASCII-safe characters only (Helvetica compatible)
// ─────────────────────────────────────────────────────────────────────────────

class AdminPdfBuilder {
  static const _primary   = PdfColor.fromInt(0xFF1A237E);
  static const _accent    = PdfColor.fromInt(0xFF388E3C);
  static const _warn      = PdfColor.fromInt(0xFFE65100);
  static const _red       = PdfColor.fromInt(0xFFC62828);
  static const _surface   = PdfColor.fromInt(0xFFF5F5F5);
  static const _greyLight = PdfColor.fromInt(0xFFE0E0E0);
  static const _greyMid   = PdfColor.fromInt(0xFF9E9E9E);
  static const _black     = PdfColor.fromInt(0xFF212121);
  static const _white     = PdfColors.white;

  // ── USER activity report ──────────────────────────────────────────────────
  static Future<Uint8List> buildUserReport(Map<String, dynamic> data) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(), bold: pw.Font.helveticaBold()),
    );

    final bookings   = (data["bookings"]  as List? ?? []);
    final totalSpent = (data["totalSpent"] as num?)?.toDouble() ?? 0;
    final user       = {
      "name":    data["userName"]    ?? "",
      "phone":   data["userPhone"]   ?? "",
      "email":   data["userEmail"]   ?? "",
      "address": data["userAddress"] ?? {},
    };
    final dateFrom = _parseDate(data["dateFrom"]);
    final dateTo   = _parseDate(data["dateTo"]);

    // Cover
    pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(0),
      build: (_) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _banner("CUSTOMER ACTIVITY REPORT",
              "${_fmtDate(dateFrom)} - ${_fmtDate(dateTo)}"),
          pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(children: [
                  pw.Expanded(child: _card("CUSTOMER", [
                    _kv("Name",  user["name"].toString()),
                    _kv("Phone", user["phone"].toString()),
                    _kv("Email", user["email"].toString()),
                  ])),
                  pw.SizedBox(width: 16),
                  pw.Expanded(child: _card("ADDRESS", [
                    _kv("Locality", (user["address"] as Map)["locality"]?.toString() ?? "-"),
                    _kv("District", (user["address"] as Map)["district"]?.toString() ?? "-"),
                    _kv("Pincode",  (user["address"] as Map)["pincode"]?.toString()  ?? "-"),
                  ])),
                  pw.SizedBox(width: 16),
                  pw.Expanded(child: _card("SUMMARY", [
                    _kv("Total Bookings", "${bookings.length}"),
                    _kv("Total Spent",    "Rs. ${totalSpent.toStringAsFixed(0)}"),
                    _kv("Period",         "${_fmtDate(dateFrom)} to ${_fmtDate(dateTo)}"),
                  ])),
                ]),
                pw.SizedBox(height: 20),
                pw.Row(children: [
                  _stat("BOOKINGS",     "${bookings.length}",                        _primary),
                  pw.SizedBox(width: 10),
                  _stat("TOTAL SPENT",  "Rs. ${totalSpent.toStringAsFixed(0)}",      _accent),
                  pw.SizedBox(width: 10),
                  _stat("COMPLETED",    "${bookings.where((b) => b["status"] == "completed").length}", _accent),
                  pw.SizedBox(width: 10),
                  _stat("PENDING",      "${bookings.where((b) => b["paymentStatus"] != "paid" && b["status"] == "completed").length}", _warn),
                ]),
                pw.SizedBox(height: 20),
                pw.Divider(color: _greyLight),
                pw.SizedBox(height: 8),
                pw.Text("Generated by Skill Renting App Admin Panel",
                    style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
              ],
            ),
          ),
        ],
      ),
    ));

    // Booking rows (MultiPage landscape)
    if (bookings.isNotEmpty) {
      pdf.addPage(_userBookingMultiPage(user, bookings, dateFrom, dateTo));
    }

    return pdf.save();
  }

  static pw.MultiPage _userBookingMultiPage(
    Map user, List bookings, DateTime from, DateTime to) {

    const colWidths = {
      0: pw.FlexColumnWidth(2.0), // Service
      1: pw.FlexColumnWidth(2.0), // Provider
      2: pw.FlexColumnWidth(2.4), // Description
      3: pw.FlexColumnWidth(1.8), // Date & Slot
      4: pw.FlexColumnWidth(1.2), // Status
      5: pw.FlexColumnWidth(1.8), // Fee
      6: pw.FlexColumnWidth(1.2), // Payment
      7: pw.FlexColumnWidth(1.4), // Rating
    };
    final hs = pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _white);
    final cs = pw.TextStyle(fontSize: 7.5, color: _black);
    final gs = pw.TextStyle(fontSize: 7,   color: _greyMid);

    return pw.MultiPage(
      pageFormat: PdfPageFormat.a4.landscape,
      margin: const pw.EdgeInsets.fromLTRB(24, 24, 24, 32),
      header: (ctx) => pw.Column(children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
              pw.Text("BOOKING HISTORY",
                  style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: _primary)),
              pw.Text("${user["name"]}  |  ${_fmtDate(from)} - ${_fmtDate(to)}",
                  style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
            ]),
            pw.Text("Page ${ctx.pageNumber} of ${ctx.pagesCount}",
                style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Table(columnWidths: colWidths, children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: _primary),
            children: ["Service","Provider","Description","Date & Slot","Status","Fee (Rs.)","Payment","Rating"]
                .map((h) => _hc(h, hs)).toList(),
          ),
        ]),
      ]),
      footer: (ctx) => pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.Text("Skill Renting App | Admin | Confidential",
            style: const pw.TextStyle(fontSize: 7, color: _greyMid)),
      ),
      build: (ctx) {
        final rows = bookings.asMap().entries.map((e) {
          final i = e.key;
          final b = Map<String, dynamic>.from(e.value as Map);
          final bg = i.isEven ? _white : _surface;
          final review = b["review"] as Map?;
          final ratingText = review == null ? "-"
              : "${List.generate(5, (i) => i < (review["rating"] as num).toInt() ? "*" : "-").join()} ${review["rating"]}/5";

          return pw.TableRow(
            decoration: pw.BoxDecoration(color: bg),
            children: [
              _dc(b["skillTitle"]?.toString() ?? "-",     cs),
              pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
                pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text(b["providerName"]?.toString()  ?? "-", style: cs),
                  pw.Text(b["providerPhone"]?.toString() ?? "-", style: gs),
                ])),
              _dc((b["description"]?.toString().length ?? 0) > 60
                  ? "${b["description"].toString().substring(0,60)}..." : b["description"]?.toString() ?? "-", cs),
              _slotDc(b, cs, gs),
              _statusBadge(b["status"]?.toString() ?? ""),
              _feeDc(b, cs),
              _payDc(b, cs),
              _dc(ratingText, cs),
            ],
          );
        }).toList();

        return [
          pw.Table(
            columnWidths: colWidths,
            border: pw.TableBorder.all(color: _greyLight, width: 0.4),
            children: rows,
          ),
          pw.SizedBox(height: 14),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              decoration: pw.BoxDecoration(color: _accent, borderRadius: pw.BorderRadius.circular(4)),
              child: pw.Text(
                "TOTAL SPENT:  Rs. ${(bookings.where((b) => (b as Map)["paymentStatus"] == "paid").fold<double>(0, (s,b) => s + ((b as Map)["totalAmount"] as num).toDouble())).toStringAsFixed(0)}",
                style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _white),
              ),
            ),
          ),
        ];
      },
    );
  }

  // ── PROVIDER report ───────────────────────────────────────────────────────
  static Future<Uint8List> buildProviderReport(Map<String, dynamic> data) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(), bold: pw.Font.helveticaBold()),
    );

    final sections   = (data["skillSections"] as List? ?? []);
    final grandTotal = (data["grandTotal"] as num?)?.toDouble() ?? 0;
    final dateFrom   = _parseDate(data["dateFrom"]);
    final dateTo     = _parseDate(data["dateTo"]);

    // Cover
    pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(0),
      build: (_) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _banner("PROVIDER ACTIVITY REPORT",
              "${_fmtDate(dateFrom)} - ${_fmtDate(dateTo)}"),
          pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(children: [
                  pw.Expanded(child: _card("PROVIDER", [
                    _kv("Name",  data["providerName"]?.toString()  ?? ""),
                    _kv("Phone", data["providerPhone"]?.toString() ?? ""),
                    _kv("Email", data["providerEmail"]?.toString() ?? ""),
                  ])),
                  pw.SizedBox(width: 16),
                  pw.Expanded(child: _card("SERVICES", [
                    _kv("Total Skills",  "${sections.length}"),
                    _kv("Report Period", "${_fmtDate(dateFrom)} to ${_fmtDate(dateTo)}"),
                  ])),
                  pw.SizedBox(width: 16),
                  pw.Expanded(child: _card("FINANCIALS", [
                    _kv("Grand Total Received", "Rs. ${grandTotal.toStringAsFixed(0)}"),
                    _kv("Total Bookings",
                        "${sections.fold<int>(0, (s, sec) => s + ((sec as Map)["bookings"] as List).length)}"),
                  ])),
                ]),
                pw.SizedBox(height: 20),
                // Per-skill summary rows
                pw.Text("SERVICE BREAKDOWN",
                    style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _primary)),
                pw.SizedBox(height: 8),
                pw.Table(
                  border: pw.TableBorder.all(color: _greyLight, width: 0.5),
                  columnWidths: {
                    0: const pw.FlexColumnWidth(3),
                    1: const pw.FlexColumnWidth(2),
                    2: const pw.FlexColumnWidth(2),
                    3: const pw.FlexColumnWidth(2),
                  },
                  children: [
                    pw.TableRow(
                      decoration: const pw.BoxDecoration(color: _primary),
                      children: ["Service","Pricing","Bookings","Received"]
                          .map((h) => _hc(h, pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _white)))
                          .toList(),
                    ),
                    ...sections.asMap().entries.map((e) {
                      final sec = Map<String, dynamic>.from(e.value as Map);
                      final bg = e.key.isEven ? _white : _surface;
                      return pw.TableRow(
                        decoration: pw.BoxDecoration(color: bg),
                        children: [
                          _dc(sec["skillTitle"]?.toString() ?? "", const pw.TextStyle(fontSize: 8)),
                          _dc("Rs. ${sec["pricePerUnit"]}/${sec["pricingUnit"]}", const pw.TextStyle(fontSize: 8)),
                          _dc("${(sec["bookings"] as List).length}", const pw.TextStyle(fontSize: 8)),
                          _dc("Rs. ${(sec["totalReceived"] as num).toStringAsFixed(0)}", const pw.TextStyle(fontSize: 8)),
                        ],
                      );
                    }),
                  ],
                ),
                pw.SizedBox(height: 16),
                pw.Divider(color: _greyLight),
                pw.SizedBox(height: 8),
                pw.Text("Generated by Skill Renting App Admin Panel",
                    style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
              ],
            ),
          ),
        ],
      ),
    ));

    // One detail section per skill
    for (final sec in sections) {
      final section = Map<String, dynamic>.from(sec as Map);
      final bookings = (section["bookings"] as List? ?? []);
      final blocked  = (section["blockedSlots"] as List? ?? []);
      if (bookings.isEmpty && blocked.isEmpty) continue;

      if (bookings.isNotEmpty) {
        pdf.addPage(_providerSkillMultiPage(
          data["providerName"]?.toString() ?? "",
          section, dateFrom, dateTo,
        ));
      }
    }

    return pdf.save();
  }

  static pw.MultiPage _providerSkillMultiPage(
    String providerName, Map<String, dynamic> section,
    DateTime from, DateTime to) {

    const colWidths = {
      0: pw.FlexColumnWidth(2.2),
      1: pw.FlexColumnWidth(1.8),
      2: pw.FlexColumnWidth(2.4),
      3: pw.FlexColumnWidth(1.8),
      4: pw.FlexColumnWidth(1.2),
      5: pw.FlexColumnWidth(1.8),
      6: pw.FlexColumnWidth(1.2),
      7: pw.FlexColumnWidth(1.6),
    };
    final hs = pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _white);
    final cs = pw.TextStyle(fontSize: 7.5, color: _black);
    final gs = pw.TextStyle(fontSize: 7,   color: _greyMid);
    final bookings = (section["bookings"] as List? ?? []);

    return pw.MultiPage(
      pageFormat: PdfPageFormat.a4.landscape,
      margin: const pw.EdgeInsets.fromLTRB(24, 24, 24, 32),
      header: (ctx) => pw.Column(children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
              pw.Text("${section["skillTitle"]}",
                  style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: _primary)),
              pw.Text("$providerName  |  Rs. ${section["pricePerUnit"]}/${section["pricingUnit"]}  |  ${_fmtDate(from)} - ${_fmtDate(to)}",
                  style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
            ]),
            pw.Text("Page ${ctx.pageNumber} of ${ctx.pagesCount}",
                style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Table(columnWidths: colWidths, children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: _primary),
            children: ["Customer","Location","Description","Date & Slot","Status","Fee (Rs.)","Payment","Rating"]
                .map((h) => _hc(h, hs)).toList(),
          ),
        ]),
      ]),
      footer: (ctx) => pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.Text("Skill Renting App | Admin | Confidential",
            style: const pw.TextStyle(fontSize: 7, color: _greyMid)),
      ),
      build: (ctx) {
        final rows = bookings.asMap().entries.map((e) {
          final i = e.key;
          final b = Map<String, dynamic>.from(e.value as Map);
          final bg = i.isEven ? _white : _surface;
          final review = b["review"] as Map?;
          final ratingText = review == null ? "-"
              : "${List.generate(5, (i) => i < (review["rating"] as num).toInt() ? "*" : "-").join()} ${review["rating"]}/5";

          return pw.TableRow(
            decoration: pw.BoxDecoration(color: bg),
            children: [
              pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
                pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text(b["seekerName"]?.toString()  ?? "-", style: cs),
                  pw.Text(b["seekerPhone"]?.toString() ?? "-", style: gs),
                ])),
              pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
                pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text(b["locality"]?.toString() ?? "-", style: cs),
                  pw.Text(b["district"]?.toString() ?? "-", style: gs),
                ])),
              _dc((b["description"]?.toString().length ?? 0) > 60
                  ? "${b["description"].toString().substring(0,60)}..." : b["description"]?.toString() ?? "-", cs),
              _slotDcRaw(
                _parseDate(b["startDate"]),
                _parseDate(b["endDate"]),
                b["feeUnit"]?.toString() ?? "hour",
                cs, gs,
              ),
              _statusBadge(b["status"]?.toString() ?? ""),
              _feeDc(b, cs),
              _payDc(b, cs),
              _dc(ratingText, cs),
            ],
          );
        }).toList();

        return [
          pw.Table(
            columnWidths: colWidths,
            border: pw.TableBorder.all(color: _greyLight, width: 0.4),
            children: rows,
          ),
          pw.SizedBox(height: 12),
          if (section["blockedSlots"] != null && (section["blockedSlots"] as List).isNotEmpty) ...[
            pw.Text("OFF / REST SLOTS",
                style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: _primary)),
            pw.SizedBox(height: 6),
            pw.Table(
              border: pw.TableBorder.all(color: _greyLight, width: 0.4),
              columnWidths: {0: const pw.FlexColumnWidth(3), 1: const pw.FlexColumnWidth(3), 2: const pw.FlexColumnWidth(4)},
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: _primary),
                  children: ["From","To","Reason"].map((h) => _hc(h, pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _white))).toList(),
                ),
                ...(section["blockedSlots"] as List).asMap().entries.map((e) {
                  final bl = Map<String, dynamic>.from(e.value as Map);
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(color: e.key.isEven ? _white : _surface),
                    children: [
                      _dc(_fmtDt(_parseDate(bl["startDate"])), const pw.TextStyle(fontSize: 7.5)),
                      _dc(_fmtDt(_parseDate(bl["endDate"])),   const pw.TextStyle(fontSize: 7.5)),
                      _dc(bl["reason"]?.toString() ?? "Off",   const pw.TextStyle(fontSize: 7.5)),
                    ],
                  );
                }),
              ],
            ),
            pw.SizedBox(height: 12),
          ],
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 8),
              decoration: pw.BoxDecoration(color: _accent, borderRadius: pw.BorderRadius.circular(4)),
              child: pw.Text(
                "RECEIVED:  Rs. ${(section["totalReceived"] as num).toStringAsFixed(0)}",
                style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _white),
              ),
            ),
          ),
        ];
      },
    );
  }

  // ── Shared helpers ────────────────────────────────────────────────────────
  static pw.Widget _banner(String title, String subtitle) =>
    pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.fromLTRB(36, 30, 36, 26),
      decoration: const pw.BoxDecoration(color: _primary),
      child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text("SKILL RENTING APP  |  ADMIN",
            style: pw.TextStyle(fontSize: 8, color: _white, fontWeight: pw.FontWeight.bold, letterSpacing: 2)),
        pw.SizedBox(height: 6),
        pw.Text(title,
            style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: _white)),
        pw.SizedBox(height: 4),
        pw.Text(subtitle, style: const pw.TextStyle(fontSize: 12, color: _white)),
      ]),
    );

  static pw.Widget _card(String title, List<pw.Widget> rows) =>
    pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: _surface,
        borderRadius: pw.BorderRadius.circular(4),
        border: pw.Border.all(color: _greyLight, width: 0.5),
      ),
      child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text(title, style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _primary, letterSpacing: 1.2)),
        pw.SizedBox(height: 8),
        ...rows,
      ]),
    );

  static pw.Widget _kv(String label, String value) =>
    pw.Padding(padding: const pw.EdgeInsets.only(bottom: 5), child:
      pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 7.5, color: _greyMid)),
        pw.Text(value, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: _black)),
      ]));

  static pw.Widget _stat(String label, String value, PdfColor color) =>
    pw.Expanded(child: pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: pw.BoxDecoration(color: color, borderRadius: pw.BorderRadius.circular(6)),
      child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text(label, style: pw.TextStyle(fontSize: 7, color: _white, letterSpacing: 0.8)),
        pw.SizedBox(height: 4),
        pw.Text(value, style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold, color: _white)),
      ]),
    ));

  static pw.Widget _hc(String t, pw.TextStyle s) =>
    pw.Padding(padding: const pw.EdgeInsets.fromLTRB(6,7,6,7), child: pw.Text(t, style: s));

  static pw.Widget _dc(String t, pw.TextStyle s) =>
    pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child: pw.Text(t, style: s));

  static pw.Widget _slotDc(Map b, pw.TextStyle cs, pw.TextStyle gs) =>
    _slotDcRaw(_parseDate(b["startDate"]), _parseDate(b["endDate"]),
        b["pricingUnit"]?.toString() ?? b["feeUnit"]?.toString() ?? "hour", cs, gs);

  static pw.Widget _slotDcRaw(DateTime start, DateTime end, String unit,
      pw.TextStyle cs, pw.TextStyle gs) {
    final date = _fmtDate(start);
    final time = unit == "hour"
        ? "${start.hour.toString().padLeft(2,'0')}:${start.minute.toString().padLeft(2,'0')} - ${end.hour.toString().padLeft(2,'0')}:${end.minute.toString().padLeft(2,'0')}"
        : "to ${_fmtDate(end)}";
    return pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
      pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text(date, style: pw.TextStyle(fontSize: 7.5, fontWeight: pw.FontWeight.bold, color: _black)),
        pw.Text(time, style: gs),
      ]));
  }

  static pw.Widget _statusBadge(String status) {
    final label = _statusLabel(status);
    final color = _statusColor(status);
    final bg    = _statusBg(status);
    return pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
      pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 3),
        decoration: pw.BoxDecoration(color: bg, borderRadius: pw.BorderRadius.circular(3),
            border: pw.Border.all(color: color, width: 0.5)),
        child: pw.Text(label, style: pw.TextStyle(fontSize: 7, color: color, fontWeight: pw.FontWeight.bold)),
      ));
  }

  static pw.Widget _feeDc(Map b, pw.TextStyle cs) {
    final status = b["status"]?.toString() ?? "";
    String text; pw.TextStyle style;
    if (status == "rejected") {
      text = "NIL"; style = pw.TextStyle(fontSize: 7.5, color: _red, fontWeight: pw.FontWeight.bold);
    } else if (status == "accepted" || status == "in_progress") {
      text = "Not Calculated"; style = pw.TextStyle(fontSize: 7.5, color: _greyMid);
    } else {
      final fee   = (b["fee"]   as num?)?.toDouble() ?? 0;
      final extra = (b["extraCharges"] as num?)?.toDouble() ?? 0;
      final total = (b["totalAmount"]  as num?)?.toDouble() ?? fee;
      text = "Base: Rs. ${fee.toStringAsFixed(0)}";
      if (extra > 0) text += "\nExtra: Rs. ${extra.toStringAsFixed(0)}";
      text += "\nTotal: Rs. ${total.toStringAsFixed(0)}";
      style = cs;
    }
    return pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child: pw.Text(text, style: style));
  }

  static pw.Widget _payDc(Map b, pw.TextStyle cs) {
    final status  = b["status"]?.toString() ?? "";
    final payment = b["paymentStatus"]?.toString() ?? "";
    String text; pw.TextStyle style;
    if (status == "rejected") {
      text = "-"; style = pw.TextStyle(fontSize: 7.5, color: _greyMid);
    } else if (status == "accepted" || status == "in_progress") {
      text = "Pending"; style = pw.TextStyle(fontSize: 7.5, color: _warn, fontWeight: pw.FontWeight.bold);
    } else if (payment == "paid") {
      text = "Received"; style = pw.TextStyle(fontSize: 7.5, color: _accent, fontWeight: pw.FontWeight.bold);
    } else {
      text = "Pending"; style = pw.TextStyle(fontSize: 7.5, color: _warn, fontWeight: pw.FontWeight.bold);
    }
    return pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child: pw.Text(text, style: style));
  }

  static String _statusLabel(String s) {
    switch (s) {
      case "accepted":    return "Accepted";
      case "in_progress": return "In Progress";
      case "completed":   return "Completed";
      case "rejected":    return "Rejected";
      case "cancelled":   return "Cancelled";
      default:            return s;
    }
  }

  static PdfColor _statusColor(String s) {
    switch (s) {
      case "accepted":    return const PdfColor.fromInt(0xFF1565C0);
      case "in_progress": return const PdfColor.fromInt(0xFF6A1B9A);
      case "completed":   return const PdfColor.fromInt(0xFF2E7D32);
      case "rejected":    return const PdfColor.fromInt(0xFFC62828);
      default:            return const PdfColor.fromInt(0xFF757575);
    }
  }

  static PdfColor _statusBg(String s) {
    switch (s) {
      case "accepted":    return const PdfColor.fromInt(0xFFE3F2FD);
      case "in_progress": return const PdfColor.fromInt(0xFFF3E5F5);
      case "completed":   return const PdfColor.fromInt(0xFFE8F5E9);
      case "rejected":    return const PdfColor.fromInt(0xFFFFEBEE);
      default:            return const PdfColor.fromInt(0xFFF5F5F5);
    }
  }

  static DateTime _parseDate(dynamic d) {
    if (d == null) return DateTime.now();
    return DateTime.tryParse(d.toString())?.toLocal() ?? DateTime.now();
  }

  static String _fmtDate(DateTime d) =>
      "${d.day.toString().padLeft(2,'0')}/${d.month.toString().padLeft(2,'0')}/${d.year}";

  static String _fmtDt(DateTime d) =>
      "${_fmtDate(d)}  ${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}";

  // ── BULK USER report ─────────────────────────────────────────────────────
  static Future<Uint8List> buildBulkUserReport(Map<String, dynamic> data) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
          base: pw.Font.helvetica(), bold: pw.Font.helveticaBold()));

    final users      = (data["users"]      as List? ?? []);
    final grandTotal = (data["grandTotal"] as num?)?.toDouble() ?? 0;
    final filters    = data["filters"]     as Map? ?? {};
    final dateFrom   = _parseDate(data["dateFrom"]);
    final dateTo     = _parseDate(data["dateTo"]);

    // Cover
    pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(0),
      build: (_) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        _banner("BULK USER REPORT",
            "${_fmtDate(dateFrom)} - ${_fmtDate(dateTo)}"),
        pw.Padding(padding: const pw.EdgeInsets.all(32), child:
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Row(children: [
              pw.Expanded(child: _card("FILTERS", [
                _kv("Role",         filters["role"]?.toString() ?? "All"),
                _kv("District",     filters["district"]?.toString() ?? "All"),
                _kv("Service Type", filters["pricingUnit"]?.toString() ?? "All"),
              ])),
              pw.SizedBox(width: 14),
              pw.Expanded(child: _card("SUMMARY", [
                _kv("Total Users",    "${users.length}"),
                _kv("Grand Total",    "Rs. ${grandTotal.toStringAsFixed(0)}"),
                _kv("Period",         "${_fmtDate(dateFrom)} to ${_fmtDate(dateTo)}"),
              ])),
            ]),
            pw.SizedBox(height: 20),
            // User summary table
            pw.Table(
              border: pw.TableBorder.all(color: _greyLight, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(2.5),
                1: const pw.FlexColumnWidth(1.5),
                2: const pw.FlexColumnWidth(1.8),
                3: const pw.FlexColumnWidth(1.5),
                4: const pw.FlexColumnWidth(1.2),
                5: const pw.FlexColumnWidth(1.5),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: _primary),
                  children: ["Name","Phone","District","Role","Bookings","Total (Rs.)"]
                      .map((h) => _hc(h, pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _white)))
                      .toList(),
                ),
                ...users.asMap().entries.map((e) {
                  final i = e.key;
                  final u = Map<String, dynamic>.from(e.value as Map);
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(color: i.isEven ? _white : _surface),
                    children: [
                      _dc(u["name"]?.toString() ?? "-",       const pw.TextStyle(fontSize: 8)),
                      _dc(u["phone"]?.toString() ?? "-",      const pw.TextStyle(fontSize: 8)),
                      _dc(u["district"]?.toString() ?? "-",   const pw.TextStyle(fontSize: 8)),
                      _dc(u["isProvider"] == true ? "Provider" : "Customer", const pw.TextStyle(fontSize: 8)),
                      _dc("${u["bookingCount"] ?? 0}",        const pw.TextStyle(fontSize: 8)),
                      _dc("Rs. ${(u["totalSpent"] as num?)?.toStringAsFixed(0) ?? '0'}", const pw.TextStyle(fontSize: 8)),
                    ],
                  );
                }),
              ],
            ),
            pw.SizedBox(height: 14),
            pw.Align(alignment: pw.Alignment.centerRight,
              child: pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                decoration: pw.BoxDecoration(color: _accent, borderRadius: pw.BorderRadius.circular(4)),
                child: pw.Text("GRAND TOTAL:  Rs. ${grandTotal.toStringAsFixed(0)}",
                    style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _white)),
              ),
            ),
          ]),
        ),
      ]),
    ));

    return pdf.save();
  }

  // ── BOOKINGS report ───────────────────────────────────────────────────────
  static Future<Uint8List> buildBookingsReport(Map<String, dynamic> data) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
          base: pw.Font.helvetica(), bold: pw.Font.helveticaBold()));

    final bookings     = (data["bookings"]     as List? ?? []);
    final totalReceived = (data["totalReceived"] as num?)?.toDouble() ?? 0;
    final dateFrom     = _parseDate(data["dateFrom"]);
    final dateTo       = _parseDate(data["dateTo"]);
    final skillTitle   = data["skillTitle"]?.toString() ?? "All Skills";

    // Cover
    pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(0),
      build: (_) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        _banner("BOOKINGS REPORT", "${_fmtDate(dateFrom)} - ${_fmtDate(dateTo)}"),
        pw.Padding(padding: const pw.EdgeInsets.all(32), child:
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Row(children: [
              pw.Expanded(child: _card("SCOPE", [
                _kv("Service",    skillTitle),
                _kv("Period",     "${_fmtDate(dateFrom)} to ${_fmtDate(dateTo)}"),
              ])),
              pw.SizedBox(width: 14),
              pw.Expanded(child: _card("SUMMARY", [
                _kv("Total Bookings", "${bookings.length}"),
                _kv("Total Received", "Rs. ${totalReceived.toStringAsFixed(0)}"),
                _kv("Completed",      "${bookings.where((b) => (b as Map)["status"] == "completed").length}"),
              ])),
            ]),
            pw.SizedBox(height: 14),
            pw.Text("Generated by Skill Renting App Admin Panel",
                style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
          ]),
        ),
      ]),
    ));

    // Detail pages
    if (bookings.isNotEmpty) {
      const colWidths = {
        0: pw.FlexColumnWidth(2.0),
        1: pw.FlexColumnWidth(2.0),
        2: pw.FlexColumnWidth(1.8),
        3: pw.FlexColumnWidth(2.0),
        4: pw.FlexColumnWidth(1.2),
        5: pw.FlexColumnWidth(1.8),
        6: pw.FlexColumnWidth(1.2),
        7: pw.FlexColumnWidth(1.6),
      };
      final hs = pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _white);
      final cs = pw.TextStyle(fontSize: 7.5, color: _black);
      final gs = pw.TextStyle(fontSize: 7,   color: _greyMid);

      pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.fromLTRB(24, 24, 24, 32),
        header: (ctx) => pw.Column(children: [
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
            pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
              pw.Text(skillTitle, style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: _primary)),
              pw.Text("${_fmtDate(dateFrom)} - ${_fmtDate(dateTo)}",
                  style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
            ]),
            pw.Text("Page ${ctx.pageNumber} of ${ctx.pagesCount}",
                style: const pw.TextStyle(fontSize: 8, color: _greyMid)),
          ]),
          pw.SizedBox(height: 8),
          pw.Table(columnWidths: colWidths, children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: _primary),
              children: ["Customer","Provider","Description","Date & Slot","Status","Fee (Rs.)","Payment","Rating"]
                  .map((h) => _hc(h, hs)).toList(),
            ),
          ]),
        ]),
        footer: (ctx) => pw.Align(alignment: pw.Alignment.centerRight,
            child: pw.Text("Skill Renting App | Admin | Confidential",
                style: const pw.TextStyle(fontSize: 7, color: _greyMid))),
        build: (ctx) {
          final rows = bookings.asMap().entries.map((e) {
            final i = e.key;
            final b = Map<String, dynamic>.from(e.value as Map);
            final bg = i.isEven ? _white : _surface;
            final review = b["review"] as Map?;
            final ratingText = review == null ? "-"
                : "${List.generate(5, (i) => i < (review["rating"] as num).toInt() ? "*" : "-").join()} ${review["rating"]}/5";

            return pw.TableRow(
              decoration: pw.BoxDecoration(color: bg),
              children: [
                pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
                  pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                    pw.Text(b["seekerName"]?.toString()  ?? "-", style: cs),
                    pw.Text(b["seekerPhone"]?.toString() ?? "-", style: gs),
                  ])),
                pw.Padding(padding: const pw.EdgeInsets.fromLTRB(5,6,5,6), child:
                  pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                    pw.Text(b["providerName"]?.toString()  ?? "-", style: cs),
                    pw.Text(b["providerPhone"]?.toString() ?? "-", style: gs),
                  ])),
                _dc((b["description"]?.toString().length ?? 0) > 60
                    ? "${b["description"].toString().substring(0,60)}..." : b["description"]?.toString() ?? "-", cs),
                _slotDcRaw(_parseDate(b["startDate"]), _parseDate(b["endDate"]),
                    b["pricingUnit"]?.toString() ?? "hour", cs, gs),
                _statusBadge(b["status"]?.toString() ?? ""),
                _feeDc(b, cs),
                _payDc(b, cs),
                _dc(ratingText, cs),
              ],
            );
          }).toList();

          return [
            pw.Table(columnWidths: colWidths,
                border: pw.TableBorder.all(color: _greyLight, width: 0.4),
                children: rows),
            pw.SizedBox(height: 14),
            pw.Align(alignment: pw.Alignment.centerRight,
              child: pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                decoration: pw.BoxDecoration(color: _accent, borderRadius: pw.BorderRadius.circular(4)),
                child: pw.Text("TOTAL RECEIVED:  Rs. ${totalReceived.toStringAsFixed(0)}",
                    style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _white)),
              ),
            ),
          ];
        },
      ));
    }

    return pdf.save();
  }
}
